### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by nadirlc** [onejgordon/flow-dashboard#105]
I tried to run the development server using the command: ./scripts/server.sh but it gave the following error:

```
(env) root@DemoContainer:/opt/flow-dashboard# ./scripts/server.sh
Starting server...
Traceback (most recent call last):
  File "/opt/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/opt/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/opt/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 414, in <module>
    main()
  File "/opt/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 402, in main
    dev_server.start(options)
  File "/opt/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 109, in start
    env_variables=parsed_env_variables)
  File "/opt/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 933, in __init__
    env_variables)
  File "/opt/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 133, in __init__
    self._config_path)
  File "/opt/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 498, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: 'app.yaml'

Running the command: ./scripts/deploy.sh 0-1 (for deploying to production server) gives the following error:

`./scripts/deploy.sh: 52: ./scripts/deploy.sh: Bad substitution`

```

**Comment by nadirlc** [comment]
We managed to fix the problem with starting the development server. The solution was to give the absolute path to the app.yaml file in ./scripts/server.sh

**Comment by nadirlc** [comment]
After running the gulp command from the source folder, it was complaining about missing module client_secrets. The problem was that in the installation instructions it was mentioned that 

./src/js/constants/client_secrets.templates.js should be copied to ./src/js/constants/clients_secrets.js. If the file is copied instead to ./src/js/constants/client_secrets.js, then the gulp error does not show

**Comment by onejgordon** [comment]
Are you running in a virtualenv as per the readme? The instructions to create the `client_secrets` file is in the readme in the 'Update code configuration' section.

**Comment by nadirlc** [comment]
Yes we are running the Flow Dashboard in a virtualenv on Debian Stretch. Our installation is working now.

I had posted the issues I came across during the installation.

**Comment by onejgordon** [comment]
Thanks @nadirlc I'll update the readme.
