### ISSUE TITLE
Gulp error while setting up the project locally

### ISSUE THREAD

**Issue by abhi18av** [onejgordon/flow-dashboard#54]
Hii @onejgordon, 

First off thanks a ton man!! I've been searching for something like this for myself - visualization help me grasp things better.

I decided to set up the project locally, following each command as documented but eventually I run into an error running `gulp`

```sh
❯ gulp
module.js:471
    throw err;
    ^

Error: Cannot find module 'lodash/lang/isFunction'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/eklavya/Projects/Polyglot/Flow/resources/flow-dashboard-0-25/node_modules/babel-core/lib/api/node.js:21:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Do you have any suggestions regarding this?

Perhaps, setting up a docker image might be a way to provide a uniform hassle-free dev. experience :)

**Comment by abhi18av** [comment]
Taking inspiration from this issue, I tried to re-install the node packages but the result is the same after a fresh `npm install` .

https://github.com/jscs-dev/node-jscs/issues/1730

**Comment by abhi18av** [comment]
Separately installing lodash with the command `npm install lodash --save` seems to have solved the issue for now.


But @onejgordon , please do consider bundling this awesome project up into a docker image :)

**Comment by onejgordon** [comment]
Glad you got it working @abhi18av. It looks like lodash was incorrectly listed in package.json as a devDep, but it's used on prod. I've updated package.json: https://github.com/onejgordon/flow-dashboard/commit/dd532807619f0cb0ee9109203a31c44598a7d944

Docker is a good idea, will be working on that in #42
